### ISSUE TITLE
TypeError: Cannot read property 'elements' of undefined

### ISSUE THREAD

**Issue by stationed** [richnologies/ngx-stripe#111]
Hello. I am currently facing an issue of having the stripe being undefined and the form elements go missing when the website is live (on https). All was good when I run on the localhost.

**On live website**
![1](https://user-images.githubusercontent.com/72121842/94649099-8d591c00-0326-11eb-8cf0-3e3742a101f7.PNG)

**On localhost**
![2](https://user-images.githubusercontent.com/72121842/94649209-c3969b80-0326-11eb-81f9-72f2fdcad3e2.PNG)

**Error on console:**
`TypeError: Cannot read property 'elements' of undefined`

![3](https://user-images.githubusercontent.com/72121842/94649113-92b66680-0326-11eb-945d-959847aa99ff.PNG)

**Versions I am using**
angular: 7.1.1
ngx-stripe: ^7.6.0
stripe: ^8.39.1

**app.module.ts**
``` 
imports: [
   NgxStripeModule.forRoot(<my-stripe-pk>)
]
```

**checkout.component.html**
```
<form id="card-form" novalidate (ngSubmit)="stripePayment($event)" [formGroup]="stripeForm">
    <input type="text" class="form-control" formControlName="name" placeholder="Name on card">
    <ngx-stripe-card [options]="cardOptions" [elementsOptions]="elementsOptions"></ngx-stripe-card>
    <button type="submit" id="payment-btn" class="btn btn-success">Make Payment</button>
</form>
 ```

**checkout.component.ts**
```
import { StripeService, StripeCardComponent, ElementOptions, ElementsOptions } from "ngx-stripe";

@ViewChild(StripeCardComponent) card: StripeCardComponent;

stripeForm: FormGroup;

elementsOptions: ElementsOptions = {
  locale: 'en'
};

cardOptions: ElementOptions = {
    style: {
      base: {
        iconColor: '#666EE8',
        color: '#31325F',
        lineHeight: '40px',
        fontWeight: 300,
        fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
        fontSize: '18px',
        '::placeholder': { color: '#CFD7E0' }
      }
    }
};

constructor(private formBuilder: FormBuilder, private stripeService: StripeService) { }

ngOnInit() {
    this.stripeForm = this.formBuilder.group({
      name: ['', [Validators.required]]
    });
}

stripePayment( ) {
    this.stripeService.createToken(this.card.getCard(), { name }).subscribe(result => {
        if (result.token) {
          // do something
       }
    });
}
```

Any help will be greatly appreciated!

**Comment by Picorete** [comment]
I have the same issue :( if you find a solution don't forget to share it!

**Comment by richnologies** [comment]
Hello @stationed, 

I believe you have mix between the new version and old one. Couple of months ago we make a huge refactor to drop our own interfaces in favor of `@stripe/stripe-js` official ones. In order to provide all the new features to old angular versions we create two branches of the project, Legacy (which represents the old version) and LTS (the new version, which we make compatible back to Angular 6).

In the readme there is a table to indicate the versions for each one. The version you're indicated ^7.6.0 represents the new version of the library for Angular 7. However, your imports in the sample code corresponds to the old version. Maybe this is way it works on development where the compiler is more forgiving, but not in production. 

I've created a stackblitz for you, is basically your example with very little changes to make it work with the new version of the library: https://stackblitz.com/edit/ngx-stripe-card-element-form?file=app/app.module.ts

Hope it helps you,

R

**Comment by alsoicode** [comment]
I have exactly the same issue, and I'm not mixing versions.

My package.json specifies exactly:

```
"@stripe/stripe-js": "1.11.0",
"ngx-stripe": "10.1.2"
```

Everything works fine running using `ng serve` as soon as I deploy my application to Heroku, it fails.

**Comment by alphacentauridigital** [comment]
Hello, 
I am also having the same issue with Angular v8.

I am getting the following error

ERROR TypeError: Cannot read property 'element' of undefined. card variable comes as undefined

`@ViewChild(StripeCardComponent, { static: true }) card: StripeCardComponent;`

My package.json contains:
`"ngx-stripe": "8.2.0",
"@stripe/stripe-js": "1.11.0"`

@alsoicode Were you able to solve this? I am getting an issue at ng serve as well. Thanks

**Comment by alphacentauridigital** [comment]
Solved by using static: false

`@ViewChild(StripeCardComponent, { static: false}) card: StripeCardComponent;`

Thanks

**Comment by alsoicode** [comment]
@alphacentauridigital @richnologies My `<ngx-stripe-card>` is inside a conditional parent fieldset, which seems to be what's causing the issue.

**Comment by richnologies** [comment]
Thanks @alphacentauridigital and @alsoicode, I'll have a look with all this new feedback.

**Comment by fxck** [comment]
Getting this as well, `ngx-stripe 10.1.2`, `stripe-js 1.13.1`

**Comment by fxck** [comment]
Ah, got it, I was using `NgxStripeModule.forChild()`, thinking it's the one exporting ngx-stripe components, but it's just `NgxStripeModule` without anything.

**Comment by ssitu-bdc** [comment]
> NgxStripeModule.forChild()

how did you resolve the issue?

**Comment by dtslvr** [comment]
> > NgxStripeModule.forChild()
> 
> how did you resolve the issue?

Please try this:

```
@NgModule({
  declarations: [SubscriptionComponent],
  exports: [],
  imports: [
    CommonModule,
    NgxStripeModule
  ],
  providers: []
})
export class SubscriptionModule {}
```

**Comment by jordanboston** [comment]
Does anyone have a solution for this yet?
`TypeError: Cannot read properties of undefined (reading 'elements')`

**Comment by alphacentauridigital** [comment]
@jordanboston  Please try this... 

> Solved by using static: false
> 
> `@ViewChild(StripeCardComponent, { static: false}) card: StripeCardComponent;`
> 
> Thanks

**Comment by jordanboston** [comment]
@alphacentauridigital I tried that but it did not resolve.  Thank you though!

**Comment by richnologies** [comment]
Agreed @jordanboston, usually the reason for this is  mismatch between public and private keys, for example using the test public key with the live private key.

**Comment by nickromanenko** [comment]
> Ah, got it, I was using `NgxStripeModule.forChild()`, thinking it's the one exporting ngx-stripe components, but it's just `NgxStripeModule` without anything.

Thanks, it fixed it for me

**Comment by rubenheymans** [comment]
for me my async await to get the clientSecret didn't work properly

**Comment by richnologies** [comment]
Hi @rubenheymans, happy to help!

Maybe is different problem, can you open a new issue and provide me with some context about your problem

Thanks,

R

**Comment by rubenheymans** [comment]
Thanks but no I meant that this was causing the issue, the load order was wrong. I already fixed it. I thought it could be a hint for others wo have this issue.

**Comment by richnologies** [comment]
My bad @rubenheymans, by all means, thanks for the help :)

**Comment by syn6UK** [comment]
I was having this issue since switching to using StripeFactoryService to initialize instead of ForRoot.

I was using stripe connect to feed in a stripeAcocunt parameter into the intialization. The value is correct and so is the public key but for some resason I'm still getting ...

`Cannot read properties of undefined (reading 'elements')`

...whenever I tried to render the component.

For me I forgot to feed the stripe instance into the component.

![image](https://user-images.githubusercontent.com/31861108/193469537-4c304a05-0828-4fc4-8f8f-e4569bf378f3.png)

**Comment by v-da100** [comment]
I will give my humble comment, for someone who has this problem and has not been able to solve it so far, the problem is due to the lack of implementation of the public key, you can add it from 

NgxStripeModule.forRoot(PUBLICKEY)

or add the public key as a property in the element like this [stripe]="stripe".

 <ngx-stripe-elements
        [stripe]="stripe"
        [elementsOptions]="elementsOptions" [elementsOptions]="elementsOptions" <ngx-stripe-elements
>
 </ngx-stripe-elements>

**Comment by SAMURAii-7** [comment]
If anyone is using ngx-stripe with angular 17+ then in the app.config.ts, include `provideNgxStripe(PUBLISHABLE_KEY)` as `NgxStripeModule.forRoot(PUBLISHABLE_KEY)` won't work inside the component's imports. I am new to angular so apologies if this was obvious.
